version: '3.3'

# Lock all version of images
services:
  nginx:
    image: nginx:1.15.8
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./statsx_content/www:/var/www/
      - ./statsx_content/logs:/var/log/nginx/
      - ./statsx_content/nginx_conf.d:/etc/nginx/conf.d
    links:
      - php
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    container_name: mysql
    # Add MYSQL_USER, MYSQL_PASSWORD to your override file
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=hlstatsx
    volumes:
      - ./statsx_content/db:/var/lib/mysql
  php:
    build: ./php-docker
    container_name: php-fpm
    volumes:
      - ./statsx_content/www:/var/www/
    links:
      - mysql

